name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ionic-buildpack-ci

    steps:
      - uses: actions/checkout@v3

      - run: npm install

      - run: ionic build --prod

      - run: ionic capacitor build android --prod

      - uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android-release/app-release.apk
